@startuml Robodogクラス図
skinparam classAttributeIconSize 0
hide circle
 
class RoboDog {
-myName
-myTime
-goodMorning
-goodAfternoon
-goodNight
-firstValue
-secondValue
'教科書にはない
-result
 
+getMyName()
+setMyName()
+setNewTime()
+getMyGreeting()
'教科書にはない
+setTwoValues()
+setAndGetResult()
}
 
@enduml